package my.com.sains.teams.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INSPECT_UPLOAD".
 */
@Entity
public class InspectUpload {

    @Id
    private String inspect_id;
    private String regis_id;
    private String exch_det_id;
    private String user_login_id;
    private String user_name;
    private String color_tag_no;
    private String inspect_date_time;
    private Double gps_lat;
    private Double gps_long;
    private String lpi_chk;
    private String lpi_chk_result;
    private String species_chk;
    private String species_chk_result;
    private String pro_mark_chk;
    private String pro_mark_chk_result;
    private String jh_hammer_chk;
    private String jh_hammer_chk_result;
    private String diameter_chk;
    private String dia_chk_result;
    private String length_chk;
    private String length_chk_result;
    private String remarks;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public InspectUpload() {
    }

    public InspectUpload(String inspect_id) {
        this.inspect_id = inspect_id;
    }

    @Generated
    public InspectUpload(String inspect_id, String regis_id, String exch_det_id, String user_login_id, String user_name, String color_tag_no, String inspect_date_time, Double gps_lat, Double gps_long, String lpi_chk, String lpi_chk_result, String species_chk, String species_chk_result, String pro_mark_chk, String pro_mark_chk_result, String jh_hammer_chk, String jh_hammer_chk_result, String diameter_chk, String dia_chk_result, String length_chk, String length_chk_result, String remarks) {
        this.inspect_id = inspect_id;
        this.regis_id = regis_id;
        this.exch_det_id = exch_det_id;
        this.user_login_id = user_login_id;
        this.user_name = user_name;
        this.color_tag_no = color_tag_no;
        this.inspect_date_time = inspect_date_time;
        this.gps_lat = gps_lat;
        this.gps_long = gps_long;
        this.lpi_chk = lpi_chk;
        this.lpi_chk_result = lpi_chk_result;
        this.species_chk = species_chk;
        this.species_chk_result = species_chk_result;
        this.pro_mark_chk = pro_mark_chk;
        this.pro_mark_chk_result = pro_mark_chk_result;
        this.jh_hammer_chk = jh_hammer_chk;
        this.jh_hammer_chk_result = jh_hammer_chk_result;
        this.diameter_chk = diameter_chk;
        this.dia_chk_result = dia_chk_result;
        this.length_chk = length_chk;
        this.length_chk_result = length_chk_result;
        this.remarks = remarks;
    }

    public String getInspect_id() {
        return inspect_id;
    }

    public void setInspect_id(String inspect_id) {
        this.inspect_id = inspect_id;
    }

    public String getRegis_id() {
        return regis_id;
    }

    public void setRegis_id(String regis_id) {
        this.regis_id = regis_id;
    }

    public String getExch_det_id() {
        return exch_det_id;
    }

    public void setExch_det_id(String exch_det_id) {
        this.exch_det_id = exch_det_id;
    }

    public String getUser_login_id() {
        return user_login_id;
    }

    public void setUser_login_id(String user_login_id) {
        this.user_login_id = user_login_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getColor_tag_no() {
        return color_tag_no;
    }

    public void setColor_tag_no(String color_tag_no) {
        this.color_tag_no = color_tag_no;
    }

    public String getInspect_date_time() {
        return inspect_date_time;
    }

    public void setInspect_date_time(String inspect_date_time) {
        this.inspect_date_time = inspect_date_time;
    }

    public Double getGps_lat() {
        return gps_lat;
    }

    public void setGps_lat(Double gps_lat) {
        this.gps_lat = gps_lat;
    }

    public Double getGps_long() {
        return gps_long;
    }

    public void setGps_long(Double gps_long) {
        this.gps_long = gps_long;
    }

    public String getLpi_chk() {
        return lpi_chk;
    }

    public void setLpi_chk(String lpi_chk) {
        this.lpi_chk = lpi_chk;
    }

    public String getLpi_chk_result() {
        return lpi_chk_result;
    }

    public void setLpi_chk_result(String lpi_chk_result) {
        this.lpi_chk_result = lpi_chk_result;
    }

    public String getSpecies_chk() {
        return species_chk;
    }

    public void setSpecies_chk(String species_chk) {
        this.species_chk = species_chk;
    }

    public String getSpecies_chk_result() {
        return species_chk_result;
    }

    public void setSpecies_chk_result(String species_chk_result) {
        this.species_chk_result = species_chk_result;
    }

    public String getPro_mark_chk() {
        return pro_mark_chk;
    }

    public void setPro_mark_chk(String pro_mark_chk) {
        this.pro_mark_chk = pro_mark_chk;
    }

    public String getPro_mark_chk_result() {
        return pro_mark_chk_result;
    }

    public void setPro_mark_chk_result(String pro_mark_chk_result) {
        this.pro_mark_chk_result = pro_mark_chk_result;
    }

    public String getJh_hammer_chk() {
        return jh_hammer_chk;
    }

    public void setJh_hammer_chk(String jh_hammer_chk) {
        this.jh_hammer_chk = jh_hammer_chk;
    }

    public String getJh_hammer_chk_result() {
        return jh_hammer_chk_result;
    }

    public void setJh_hammer_chk_result(String jh_hammer_chk_result) {
        this.jh_hammer_chk_result = jh_hammer_chk_result;
    }

    public String getDiameter_chk() {
        return diameter_chk;
    }

    public void setDiameter_chk(String diameter_chk) {
        this.diameter_chk = diameter_chk;
    }

    public String getDia_chk_result() {
        return dia_chk_result;
    }

    public void setDia_chk_result(String dia_chk_result) {
        this.dia_chk_result = dia_chk_result;
    }

    public String getLength_chk() {
        return length_chk;
    }

    public void setLength_chk(String length_chk) {
        this.length_chk = length_chk;
    }

    public String getLength_chk_result() {
        return length_chk_result;
    }

    public void setLength_chk_result(String length_chk_result) {
        this.length_chk_result = length_chk_result;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
