package my.com.sains.teams.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LOG_REGISTER".
 */
@Entity
public class LogRegister {

    @Id
    private String exch_det_id;
    private String exch_id;
    private String regis_id;
    private String coupe_no;
    private String block_no;
    private String camp_code;
    private String lpi_no;
    private String log_serial_no;
    private String species_code;
    private String pro_mark_reg_no;
    private Double length;
    private Double diameter;
    private Double defect_dia;
    private Double net_vol;
    private Double compute_vol;
    private String spec_check;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LogRegister() {
    }

    public LogRegister(String exch_det_id) {
        this.exch_det_id = exch_det_id;
    }

    @Generated
    public LogRegister(String exch_det_id, String exch_id, String regis_id, String coupe_no, String block_no, String camp_code, String lpi_no, String log_serial_no, String species_code, String pro_mark_reg_no, Double length, Double diameter, Double defect_dia, Double net_vol, Double compute_vol, String spec_check) {
        this.exch_det_id = exch_det_id;
        this.exch_id = exch_id;
        this.regis_id = regis_id;
        this.coupe_no = coupe_no;
        this.block_no = block_no;
        this.camp_code = camp_code;
        this.lpi_no = lpi_no;
        this.log_serial_no = log_serial_no;
        this.species_code = species_code;
        this.pro_mark_reg_no = pro_mark_reg_no;
        this.length = length;
        this.diameter = diameter;
        this.defect_dia = defect_dia;
        this.net_vol = net_vol;
        this.compute_vol = compute_vol;
        this.spec_check = spec_check;
    }

    public String getExch_det_id() {
        return exch_det_id;
    }

    public void setExch_det_id(String exch_det_id) {
        this.exch_det_id = exch_det_id;
    }

    public String getExch_id() {
        return exch_id;
    }

    public void setExch_id(String exch_id) {
        this.exch_id = exch_id;
    }

    public String getRegis_id() {
        return regis_id;
    }

    public void setRegis_id(String regis_id) {
        this.regis_id = regis_id;
    }

    public String getCoupe_no() {
        return coupe_no;
    }

    public void setCoupe_no(String coupe_no) {
        this.coupe_no = coupe_no;
    }

    public String getBlock_no() {
        return block_no;
    }

    public void setBlock_no(String block_no) {
        this.block_no = block_no;
    }

    public String getCamp_code() {
        return camp_code;
    }

    public void setCamp_code(String camp_code) {
        this.camp_code = camp_code;
    }

    public String getLpi_no() {
        return lpi_no;
    }

    public void setLpi_no(String lpi_no) {
        this.lpi_no = lpi_no;
    }

    public String getLog_serial_no() {
        return log_serial_no;
    }

    public void setLog_serial_no(String log_serial_no) {
        this.log_serial_no = log_serial_no;
    }

    public String getSpecies_code() {
        return species_code;
    }

    public void setSpecies_code(String species_code) {
        this.species_code = species_code;
    }

    public String getPro_mark_reg_no() {
        return pro_mark_reg_no;
    }

    public void setPro_mark_reg_no(String pro_mark_reg_no) {
        this.pro_mark_reg_no = pro_mark_reg_no;
    }

    public Double getLength() {
        return length;
    }

    public void setLength(Double length) {
        this.length = length;
    }

    public Double getDiameter() {
        return diameter;
    }

    public void setDiameter(Double diameter) {
        this.diameter = diameter;
    }

    public Double getDefect_dia() {
        return defect_dia;
    }

    public void setDefect_dia(Double defect_dia) {
        this.defect_dia = defect_dia;
    }

    public Double getNet_vol() {
        return net_vol;
    }

    public void setNet_vol(Double net_vol) {
        this.net_vol = net_vol;
    }

    public Double getCompute_vol() {
        return compute_vol;
    }

    public void setCompute_vol(Double compute_vol) {
        this.compute_vol = compute_vol;
    }

    public String getSpec_check() {
        return spec_check;
    }

    public void setSpec_check(String spec_check) {
        this.spec_check = spec_check;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
