package my.com.sains.teams.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MOBILE_DOC".
 */
@Entity
public class MobileDoc {

    @Id
    private String exch_id;
    private String office_id;
    private String device_id;
    private String doc_type;
    private String source_doc_id;
    private String name;
    private Integer total_logs;
    private String batch_no;
    private String license_type;
    private String acct_code;
    private String hammer_mark_no;
    private String forest_type;
    private String type_of_produce;
    private String trp_ref_no;
    private String security_no;
    private String tran_mode;
    private String by_name;
    private String rp_no;
    private String rp_book_no;
    private String barge_raft;
    private String frm_loc;
    private String to_loc;
    private String receiving_office;
    private String issueing_office;
    private String trp_date_issued;
    private String trp_date_expire;
    private String trp_issued_by;
    private String ecc_excc_no;
    private String ecc_excc_issue_date;
    private String sh_ref_no;
    private String sh_reason;
    private String exch_status;
    private String sync_status;
    private String sync_date;
    private String created_by;
    private String created_date;
    private String modified_by;
    private String modified_date;
    private String modified_src;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MobileDoc() {
    }

    public MobileDoc(String exch_id) {
        this.exch_id = exch_id;
    }

    @Generated
    public MobileDoc(String exch_id, String office_id, String device_id, String doc_type, String source_doc_id, String name, Integer total_logs, String batch_no, String license_type, String acct_code, String hammer_mark_no, String forest_type, String type_of_produce, String trp_ref_no, String security_no, String tran_mode, String by_name, String rp_no, String rp_book_no, String barge_raft, String frm_loc, String to_loc, String receiving_office, String issueing_office, String trp_date_issued, String trp_date_expire, String trp_issued_by, String ecc_excc_no, String ecc_excc_issue_date, String sh_ref_no, String sh_reason, String exch_status, String sync_status, String sync_date, String created_by, String created_date, String modified_by, String modified_date, String modified_src) {
        this.exch_id = exch_id;
        this.office_id = office_id;
        this.device_id = device_id;
        this.doc_type = doc_type;
        this.source_doc_id = source_doc_id;
        this.name = name;
        this.total_logs = total_logs;
        this.batch_no = batch_no;
        this.license_type = license_type;
        this.acct_code = acct_code;
        this.hammer_mark_no = hammer_mark_no;
        this.forest_type = forest_type;
        this.type_of_produce = type_of_produce;
        this.trp_ref_no = trp_ref_no;
        this.security_no = security_no;
        this.tran_mode = tran_mode;
        this.by_name = by_name;
        this.rp_no = rp_no;
        this.rp_book_no = rp_book_no;
        this.barge_raft = barge_raft;
        this.frm_loc = frm_loc;
        this.to_loc = to_loc;
        this.receiving_office = receiving_office;
        this.issueing_office = issueing_office;
        this.trp_date_issued = trp_date_issued;
        this.trp_date_expire = trp_date_expire;
        this.trp_issued_by = trp_issued_by;
        this.ecc_excc_no = ecc_excc_no;
        this.ecc_excc_issue_date = ecc_excc_issue_date;
        this.sh_ref_no = sh_ref_no;
        this.sh_reason = sh_reason;
        this.exch_status = exch_status;
        this.sync_status = sync_status;
        this.sync_date = sync_date;
        this.created_by = created_by;
        this.created_date = created_date;
        this.modified_by = modified_by;
        this.modified_date = modified_date;
        this.modified_src = modified_src;
    }

    public String getExch_id() {
        return exch_id;
    }

    public void setExch_id(String exch_id) {
        this.exch_id = exch_id;
    }

    public String getOffice_id() {
        return office_id;
    }

    public void setOffice_id(String office_id) {
        this.office_id = office_id;
    }

    public String getDevice_id() {
        return device_id;
    }

    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

    public String getDoc_type() {
        return doc_type;
    }

    public void setDoc_type(String doc_type) {
        this.doc_type = doc_type;
    }

    public String getSource_doc_id() {
        return source_doc_id;
    }

    public void setSource_doc_id(String source_doc_id) {
        this.source_doc_id = source_doc_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getTotal_logs() {
        return total_logs;
    }

    public void setTotal_logs(Integer total_logs) {
        this.total_logs = total_logs;
    }

    public String getBatch_no() {
        return batch_no;
    }

    public void setBatch_no(String batch_no) {
        this.batch_no = batch_no;
    }

    public String getLicense_type() {
        return license_type;
    }

    public void setLicense_type(String license_type) {
        this.license_type = license_type;
    }

    public String getAcct_code() {
        return acct_code;
    }

    public void setAcct_code(String acct_code) {
        this.acct_code = acct_code;
    }

    public String getHammer_mark_no() {
        return hammer_mark_no;
    }

    public void setHammer_mark_no(String hammer_mark_no) {
        this.hammer_mark_no = hammer_mark_no;
    }

    public String getForest_type() {
        return forest_type;
    }

    public void setForest_type(String forest_type) {
        this.forest_type = forest_type;
    }

    public String getType_of_produce() {
        return type_of_produce;
    }

    public void setType_of_produce(String type_of_produce) {
        this.type_of_produce = type_of_produce;
    }

    public String getTrp_ref_no() {
        return trp_ref_no;
    }

    public void setTrp_ref_no(String trp_ref_no) {
        this.trp_ref_no = trp_ref_no;
    }

    public String getSecurity_no() {
        return security_no;
    }

    public void setSecurity_no(String security_no) {
        this.security_no = security_no;
    }

    public String getTran_mode() {
        return tran_mode;
    }

    public void setTran_mode(String tran_mode) {
        this.tran_mode = tran_mode;
    }

    public String getBy_name() {
        return by_name;
    }

    public void setBy_name(String by_name) {
        this.by_name = by_name;
    }

    public String getRp_no() {
        return rp_no;
    }

    public void setRp_no(String rp_no) {
        this.rp_no = rp_no;
    }

    public String getRp_book_no() {
        return rp_book_no;
    }

    public void setRp_book_no(String rp_book_no) {
        this.rp_book_no = rp_book_no;
    }

    public String getBarge_raft() {
        return barge_raft;
    }

    public void setBarge_raft(String barge_raft) {
        this.barge_raft = barge_raft;
    }

    public String getFrm_loc() {
        return frm_loc;
    }

    public void setFrm_loc(String frm_loc) {
        this.frm_loc = frm_loc;
    }

    public String getTo_loc() {
        return to_loc;
    }

    public void setTo_loc(String to_loc) {
        this.to_loc = to_loc;
    }

    public String getReceiving_office() {
        return receiving_office;
    }

    public void setReceiving_office(String receiving_office) {
        this.receiving_office = receiving_office;
    }

    public String getIssueing_office() {
        return issueing_office;
    }

    public void setIssueing_office(String issueing_office) {
        this.issueing_office = issueing_office;
    }

    public String getTrp_date_issued() {
        return trp_date_issued;
    }

    public void setTrp_date_issued(String trp_date_issued) {
        this.trp_date_issued = trp_date_issued;
    }

    public String getTrp_date_expire() {
        return trp_date_expire;
    }

    public void setTrp_date_expire(String trp_date_expire) {
        this.trp_date_expire = trp_date_expire;
    }

    public String getTrp_issued_by() {
        return trp_issued_by;
    }

    public void setTrp_issued_by(String trp_issued_by) {
        this.trp_issued_by = trp_issued_by;
    }

    public String getEcc_excc_no() {
        return ecc_excc_no;
    }

    public void setEcc_excc_no(String ecc_excc_no) {
        this.ecc_excc_no = ecc_excc_no;
    }

    public String getEcc_excc_issue_date() {
        return ecc_excc_issue_date;
    }

    public void setEcc_excc_issue_date(String ecc_excc_issue_date) {
        this.ecc_excc_issue_date = ecc_excc_issue_date;
    }

    public String getSh_ref_no() {
        return sh_ref_no;
    }

    public void setSh_ref_no(String sh_ref_no) {
        this.sh_ref_no = sh_ref_no;
    }

    public String getSh_reason() {
        return sh_reason;
    }

    public void setSh_reason(String sh_reason) {
        this.sh_reason = sh_reason;
    }

    public String getExch_status() {
        return exch_status;
    }

    public void setExch_status(String exch_status) {
        this.exch_status = exch_status;
    }

    public String getSync_status() {
        return sync_status;
    }

    public void setSync_status(String sync_status) {
        this.sync_status = sync_status;
    }

    public String getSync_date() {
        return sync_date;
    }

    public void setSync_date(String sync_date) {
        this.sync_date = sync_date;
    }

    public String getCreated_by() {
        return created_by;
    }

    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    public String getCreated_date() {
        return created_date;
    }

    public void setCreated_date(String created_date) {
        this.created_date = created_date;
    }

    public String getModified_by() {
        return modified_by;
    }

    public void setModified_by(String modified_by) {
        this.modified_by = modified_by;
    }

    public String getModified_date() {
        return modified_date;
    }

    public void setModified_date(String modified_date) {
        this.modified_date = modified_date;
    }

    public String getModified_src() {
        return modified_src;
    }

    public void setModified_src(String modified_src) {
        this.modified_src = modified_src;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
