package my.com.sains.teams.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private String security_user_login_id;
    private String security_user_name;
    private String security_user_status;
    private String security_user_password;
    private String modified_by;
    private String modified_date;
    private String modified_src;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public User() {
    }

    public User(String security_user_login_id) {
        this.security_user_login_id = security_user_login_id;
    }

    @Generated
    public User(String security_user_login_id, String security_user_name, String security_user_status, String security_user_password, String modified_by, String modified_date, String modified_src) {
        this.security_user_login_id = security_user_login_id;
        this.security_user_name = security_user_name;
        this.security_user_status = security_user_status;
        this.security_user_password = security_user_password;
        this.modified_by = modified_by;
        this.modified_date = modified_date;
        this.modified_src = modified_src;
    }

    public String getSecurity_user_login_id() {
        return security_user_login_id;
    }

    public void setSecurity_user_login_id(String security_user_login_id) {
        this.security_user_login_id = security_user_login_id;
    }

    public String getSecurity_user_name() {
        return security_user_name;
    }

    public void setSecurity_user_name(String security_user_name) {
        this.security_user_name = security_user_name;
    }

    public String getSecurity_user_status() {
        return security_user_status;
    }

    public void setSecurity_user_status(String security_user_status) {
        this.security_user_status = security_user_status;
    }

    public String getSecurity_user_password() {
        return security_user_password;
    }

    public void setSecurity_user_password(String security_user_password) {
        this.security_user_password = security_user_password;
    }

    public String getModified_by() {
        return modified_by;
    }

    public void setModified_by(String modified_by) {
        this.modified_by = modified_by;
    }

    public String getModified_date() {
        return modified_date;
    }

    public void setModified_date(String modified_date) {
        this.modified_date = modified_date;
    }

    public String getModified_src() {
        return modified_src;
    }

    public void setModified_src(String modified_src) {
        this.modified_src = modified_src;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
